"""create_users_table

Revision ID: 4822ac38538d
Revises: c6e72f9f577a
Create Date: 2025-06-05 17:36:26.579573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4822ac38538d'
down_revision: Union[str, None] = 'c6e72f9f577a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
gender_enum = sa.Enum('male', 'female', name='gender_types')
activity_levels_enum = sa.Enum('sedentary', 'light', 'moderate', 'active', 'extra', name='activity_levels')
goal_types_enum = sa.Enum(
    'lose', 'maintain', 'gain', 'custom',
    name='goal_types'
)
def upgrade() -> None:
    """Upgrade schema."""
    gender_enum.create(op.get_bind(), checkfirst=True)
    activity_levels_enum.create(op.get_bind())
    goal_types_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', name='gender_types'), nullable=False))
    op.add_column('users', sa.Column('weight_kg', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('height_cm', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'extra', name='activity_levels'), nullable=False))
    op.add_column('users', sa.Column('goal', sa.Enum('lose', 'maintain', 'gain', 'custom', name='goal_types'), nullable=False))
    op.add_column('users', sa.Column('target_calories', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'target_calories')
    op.drop_column('users', 'goal')
    op.drop_column('users', 'activity_level')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'weight_kg')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
